version: "3.9"
services:
  forwarder:
    build: ./forwarder
    ports:
    - "30443:30443"
    environment:
    - COLLECTOR_ADDR=collector:4317
    depends_on:
    - collector
  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
    - ./collector/config-prometheus.yaml:/etc/otel/config.yaml
    ports:
    - "4317:4317"
    - "4318:4318"
    - "9990:9990"
    - "8888:8888"
    depends_on:
    - prometheus
  prometheus:
    image: prom/prometheus:v2.30.0
    volumes:
    - ./prometheus/config.yaml:/etc/prometheus/config.yaml
    entrypoint: ['prometheus', '--config.file', '/etc/prometheus/config.yaml']
    ports:
    - "9090:9090"
  grafana:
    image: grafana/grafana:8.1.5
    ports:
    - "3000:3000"
    user: "104"
    volumes:
    - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    - ./grafana/reporting-api-dashboard.json:/var/lib/grafana/dashboards/reporting-api-dashboard.json
    environment:
    - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
    - prometheus