version: "3.9"
services:
  forwarder:
    build: ./forwarder
    ports:
    - "30443:30443"
  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
    - ~/.config/gcloud/application_default_credentials.json:/etc/otel/key.json
    - ./collector/config.yaml:/etc/otel/config.yaml
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/etc/otel/key.json
    ports:
    - "4317:4317"
    - "55681:55681"
    - "9990:9990"
    - "8888:8888"
## Uncomment `prometheus` section if you want to try locally
#  prometheus:
#    image: prom/prometheus:v2.30.0
#    volumes:
#    - ./prometheus/config.yaml:/etc/prometheus/config.yaml
#    entrypoint: ['prometheus', '--config.file', '/etc/prometheus/config.yaml']
#    ports:
#    - "9090:9090"
