receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  googlecloud:
    project: ${PROJECT_ID}
    user_agent: reporting-api-collector {{version}}
    use_insecure: true
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 120s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 100
  logging:
    loglevel: debug
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800
  batch:
extensions:
  health_check:
service:
  extensions:
   - health_check
  pipelines:
    metrics:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      exporters:
      - googlecloud
      - logging
