receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  googlecloud:
    project: yoshifumi-cloud-demo
    user_agent: reporting-api-collector {{version}}
    use_insecure: true
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 120s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 100
  logging:
    loglevel: debug
## Uncomment prometheus section if you want to try locally
#  prometheus:
#    endpoint: 0.0.0.0:9990
#    namespace: reporting-api-demo
#    send_timestamps: true
#    metric_expiration: 30m
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800
  batch:
service:
  pipelines:
    metrics:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      exporters:
      - googlecloud
      - logging
#      - prometheus # Uncomment this line if you want to try locally
